### ISSUE TITLE
await alipaySdk.exec(method, params, options)调用异常

### ISSUE THREAD

**Issue by codeWinson** [ali-sdk/alipay-sdk#1]
{ accessToken: 'accessToken',
  alipayUserId: '****',
  expiresIn: 1296000,
  reExpiresIn: 2592000,
  refreshToken: 'refreshToken',
  userId: 'userId' }
![image](https://user-images.githubusercontent.com/32981007/43178569-a803988c-9000-11e8-8dc0-472b9a0b9911.png)
![image](https://user-images.githubusercontent.com/32981007/43178585-b9f864aa-9000-11e8-9b25-7aa204d3fcdd.png)
![image](https://user-images.githubusercontent.com/32981007/43178850-2139188e-9002-11e8-8c7c-81f00077a47d.png)
![image](https://user-images.githubusercontent.com/32981007/43179825-76edd6ca-9007-11e8-995b-4babcf398cb2.png)
![image](https://user-images.githubusercontent.com/32981007/43180092-bce83994-9008-11e8-8931-c054ff26f776.png)

**Comment by codeWinson** [comment]
{ accessToken: 'accessToken',
  alipayUserId: '20880043392382423908664532112385',
  expiresIn: 1296000,
  reExpiresIn: 2592000,
  refreshToken: 'refreshToken',
  userId: 'userId' }
![image](https://user-images.githubusercontent.com/32981007/43178569-a803988c-9000-11e8-8dc0-472b9a0b9911.png)
![image](https://user-images.githubusercontent.com/32981007/43178585-b9f864aa-9000-11e8-9b25-7aa204d3fcdd.png)

小白求教，如何解构获取accessToken？

**Comment by codeWinson** [comment]
![image](https://user-images.githubusercontent.com/32981007/43178850-2139188e-9002-11e8-8c7c-81f00077a47d.png)

**Comment by codeWinson** [comment]
![image](https://user-images.githubusercontent.com/32981007/43179825-76edd6ca-9007-11e8-995b-4babcf398cb2.png)

**Comment by codeWinson** [comment]
![image](https://user-images.githubusercontent.com/32981007/43180092-bce83994-9008-11e8-8931-c054ff26f776.png)

**Comment by tudou527** [comment]
`exec` 返回的基础类型是  `AlipaySdkCommonResult` 你可以这样写：

```
interface IOauthToken extends AlipaySdkCommonResult {
  accessToken: string;
  alipayUserId: string;
  expiresIn: number;
  reExpiresIn: number;
  refreshToken: string;
  userId: string;
}

await alipaySdk.exec('alipay.system.oauth.token', { ... }, { ... })
  .then((res: IOauthToken) => {
    const token = res.accessToken;
  });
```

**Comment by codeWinson** [comment]
@tudou527  好像行。await alipaySdk.exec(method, params)正常，await alipaySdk.exec(method, params, options)报错，添加options时，需要检查哪里的配置吗
![1533891673 1](https://user-images.githubusercontent.com/32981007/43949054-0316c762-9c7c-11e8-94d4-0b6641a563b5.jpg)

**Comment by codeWinson** [comment]
![1533892427 1](https://user-images.githubusercontent.com/32981007/43949673-bb2103bc-9c7d-11e8-82bd-a904d1d8806f.jpg)

**Comment by tudou527** [comment]
`IOauthToken` 你定义在哪里的，这个提示是找不到这个定义。

**Comment by codeWinson** [comment]
@tudou527

**Comment by codeWinson** [comment]
@tudou527 问题二解决了，问题一中，传options时报错，是什么原因呢

**Comment by tudou527** [comment]
贴代码出来看看

**Comment by codeWinson** [comment]
``
